version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345qwerty
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  django:
    container_name: tree_project
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "
             python /usr/src/tree_project/manage.py makemigrations --noinput &&
             python /usr/src/tree_project/manage.py migrate --noinput &&
             python /usr/src/tree_project/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/tree_project
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: